---
deployment:
  tasks:
    # 1. Go to the project directory where cPanel cloned your Git repo
    - export PROJECTPATH=/home/flezqiyl/app_source

    # 2. Location to publish the built site
    - export DEPLOYPATH=/home/flezqiyl/public_html

    # 3. Install dependencies
    - cd $PROJECTPATH && npm install

    # 4. Build your Vite/React app
    - cd $PROJECTPATH && npm run build

    # 5. Clear public_html before copying new build
    - /bin/rm -rf ${DEPLOYPATH}/*

    # 6. Copy built files from dist/ to public_html
    - /bin/cp -r ${PROJECTPATH}/dist/* ${DEPLOYPATH}/
