---
deployment:
  tasks:
    - export PROJECTPATH=/home/flezqiyl/repositories/tempo-trak-platform-67ebcb84
    - export DEPLOYPATH=/home/flezqiyl/public_html/admin
    - cd $PROJECTPATH && npm install
    - cd $PROJECTPATH && npm run build
    - /bin/rm -rf ${DEPLOYPATH}/*
    - /bin/cp -r ${PROJECTPATH}/dist/* ${DEPLOYPATH}/
