---
deployment:
  tasks:
    - npm install
    - npm run build
    - /bin/rm -rf /home/flezqiyl/public_html/admin/*
    - /bin/cp -r /home/flezqiyl/repositories/tempo-trak-platform-67ebcb84/dist/* /home/flezqiyl/public_html/admin/
